fix: use expiryDate to warn close api key expiry date
kili-technology/kili-python-sdk pull request #1031
Opened 2023-02-20 16:24 UTC by theodu

2023-02-20 16:27 UTC, PierreLeveau requested changes

2023-02-20 16:27 UTC, PierreLeveau commented on src/kili/authentication.py
> +            fields=["createdAt", "expiryDate"],
```suggestion
            fields=["expiryDate"],
```

2023-02-20 16:35 UTC, Jonas1312 approved these changes

2023-02-20 17:14 UTC, hugo-mailfait-kili approved these changes

2023-02-21 07:43 UTC, PierreLeveau approved these changes

2023-02-21 07:43 UTC, merged