fix: fix coco bbox format
kili-technology/kili-python-sdk pull request #1036
Opened 2023-02-22 12:53 UTC by theodu

2023-02-22 12:53 UTC, theodu commented
COCO format: https://cocodataset.org/#format-data

> 1. Object Detection
Each object instance annotation contains a series of fields, including the category id and segmentation mask of the object. The segmentation format depends on whether the instance represents a single object (iscrowd=0 in which case polygons are used) or a collection of objects (iscrowd=1 in which case RLE is used). Note that a single object (iscrowd=0) may require multiple polygons, for example if occluded. Crowd annotations (iscrowd=1) are used to label large groups of objects (e.g. a crowd of people). In addition, an enclosing bounding box is provided for each object (box coordinates are measured from the top left image corner and are 0-indexed). Finally, the categories field of the annotation structure stores the mapping of category id to category and supercategory names. See also the [detection](https://cocodataset.org/#detection-2020) task.

2023-02-22 13:44 UTC, Jonas1312 approved these changes

2023-02-22 13:55 UTC, PierreLeveau requested changes

2023-02-22 13:55 UTC, PierreLeveau commented on src/kili/services/export/format/coco/__init__.py
> +                bbox=[int(x_min), int(y_min), int(_w_), int(_h_)],
to make sure this does not happen again, can we add a unit test? if can be worth it to extract a method `_get_coco_bbox_from_kili_bpoly`

2023-02-23 08:25 UTC, PierreLeveau approved these changes

2023-02-23 08:25 UTC, merged