feat: add create_issues and create_questions method
kili-technology/kili-python-sdk pull request #1038
Opened 2023-02-22 15:54 UTC by theodu

2023-02-22 16:59 UTC, Jonas1312 approved these changes

2023-02-22 17:02 UTC, Jonas1312 commented on src/kili/mutations/issue/__init__.py
> +            " instead. These new methods allows to import several issues or questions at the same"
allow

2023-02-22 17:02 UTC, Jonas1312 commented on src/kili/mutations/issue/__init__.py
> +            These new methods allows to import several issues or questions at the same time
allow

2023-02-23 13:34 UTC, PierreLeveau approved these changes

2023-02-24 08:28 UTC, PierreLeveau requested changes

2023-02-24 08:28 UTC, PierreLeveau commented on src/kili/mutations/issue/__init__.py
> +        if asset_external_id_array is not None and asset_id_array is None:
`get_asset_ids_or_throw_error` can be used instead

2023-02-24 10:40 UTC, PierreLeveau approved these changes

2023-02-24 10:41 UTC, merged