chore: deprecate status_array
kili-technology/kili-python-sdk pull request #1045
Opened 2023-02-27 17:17 UTC by Jonas1312

2023-02-27 17:34 UTC, theodu requested changes

2023-02-27 17:34 UTC, theodu commented on src/kili/mutations/asset/__init__.py
> +                "status_array is deprecated, use the workflow management in the Kili app instead.",
```suggestion
                "status_array is deprecated, asset status is automatically computed based on its labels and cannot be overwritten.",
```

2023-02-28 08:35 UTC, theodu approved these changes

2023-02-28 08:41 UTC, PierreLeveau approved these changes

2023-02-28 08:49 UTC, merged