docs: update
kili-technology/kili-python-sdk pull request #1067
Opened 2023-03-03 10:51 UTC by Jonas1312

2023-03-03 11:02 UTC, PierreLeveau requested changes

2023-03-03 11:02 UTC, PierreLeveau commented on recipes/set_up_workflows.ipynb
> +    "kili.delete_project(project_id);"
remove semi-column

2023-03-03 15:22 UTC, PierreLeveau approved these changes

2023-03-09 14:29 UTC, Jonas1312 commented
@PierreLeveau  we can merge this one, Przemek approves

2023-03-09 16:17 UTC, merged