feat: log client info in requests
kili-technology/kili-python-sdk pull request #1070
Opened 2023-03-03 15:12 UTC by PierreLeveau

This adds the client info (name, version, language, method) into the request headers. 

this gives:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1255753/222760132-c3b87128-8ae9-49c7-be4f-a1b0606ccdac.png">

2023-03-03 15:24 UTC, PierreLeveau commented on src/kili/graphql/graphql_client.py
> +            assert self._gql_transport.headers
self._gql_transport.headers can be None
so I'm adding a message.

2023-03-03 15:26 UTC, Jonas1312 approved these changes

2023-03-06 10:05 UTC, theodu requested changes

2023-03-06 10:05 UTC, theodu commented on tests/graphql/test_graphql_client.py
> +import mock
there were already a file tests/test_graphql_client.py 
Can we add the test inside in this new file too ?

2023-03-06 10:05 UTC, theodu commented on tests/graphql/test_graphql_client.py
> +    }
don't we add a test to test that we have the right kili-client-method-name called ?

2023-03-08 08:37 UTC, theodu approved these changes
very impressive!

2023-03-08 08:39 UTC, Jonas1312 approved these changes
I tested it, works great

2023-03-08 08:39 UTC, Jonas1312 commented on src/kili/utils/logcontext.py
> +    Utitility meta-class to guarantee single instance
typo

2023-03-08 09:22 UTC, merged