fix: Update setup.py for typeguard
kili-technology/kili-python-sdk pull request #1102
Opened 2023-03-16 07:07 UTC by Jonas1312

2023-03-16 09:18 UTC, PierreLeveau requested changes

2023-03-16 09:18 UTC, PierreLeveau commented on setup.py
> +    "typeguard==3.0.1",
`>=3.0.1`

2023-03-16 10:16 UTC, Jonas1312 commented
I found another bug in typeguard, I'll report it to the typeguard dev

don't merge this PR until the bug is fixed

2023-04-02 06:43 UTC, Jonas1312 commented
4.0.0rc1 is out

2023-06-28 05:59 UTC, closed without merging