feat: add helper to create bbox labels
kili-technology/kili-python-sdk pull request #1118
Opened 2023-03-22 12:48 UTC by Jonas1312

2023-03-22 15:28 UTC, PierreLeveau requested changes

2023-03-24 17:29 UTC, Jonas1312 commented on src/kili/label_helpers/__init__.py
I put it in kili.utils.labels with the label parser

2023-03-24 17:30 UTC, Jonas1312 commented on mkdocs.yml
> +          - Label Creation Helpers: sdk/label_helpers.md
You want to create a section Utils and Labels as a subsection?

we only have label utils for now, so not sure if it's useful

2023-03-24 17:31 UTC, Jonas1312 commented
the feature and tests require numpy + opencv

numpy is already a dependency of pandas

I didn't add opencv because it's a big dependency for such small module

2023-03-27 06:42 UTC, PierreLeveau commented on mkdocs.yml
> +          - Label Creation Helpers: sdk/label_helpers.md
ok I'm fine with keeping it this way then

2023-03-27 15:10 UTC, PierreLeveau requested changes

2023-03-27 15:10 UTC, PierreLeveau commented on src/kili/utils/labels/bbox.py
> +
asset that image width and height are both defined or both not defined

2023-03-27 15:10 UTC, PierreLeveau commented on src/kili/utils/labels/image.py
> +        "OpenCV and Numpy are required to use the image label creation helpers."
add " To install them, please run `pip install kili[image-utils]` "

2023-03-27 15:10 UTC, PierreLeveau commented on src/kili/utils/labels/point.py
> +    A point is a dict with keys 'x' and 'y', and corresponding values in pixels (int or float).
where is the origin of the input point ?

2023-03-27 15:23 UTC, PierreLeveau commented on docs/sdk/tutorials/pixel_level_masks.md
> +        "boundingPoly": [{"normalizedVertices": contours[0]}],
you mean in this example ?

2023-03-27 15:40 UTC, Jonas1312 commented on docs/sdk/tutorials/pixel_level_masks.md
> +        "boundingPoly": [{"normalizedVertices": contours[0]}],
yes in this tutorial

2023-03-28 06:37 UTC, PierreLeveau commented on docs/sdk/tutorials/pixel_level_masks.md
> +        "boundingPoly": [{"normalizedVertices": contours[0]}],
since this code can be copy-pasted, `[{"normalizedVertices": contour} for contour in contours]` is better.

2023-03-28 06:39 UTC, PierreLeveau requested changes

2023-03-28 06:39 UTC, PierreLeveau commented on src/kili/utils/labels/point.py
> +    If the image width and height are provided, the point coordinates will be normalized to [0, 1].
can you add this to the docstring?

2023-03-28 06:39 UTC, PierreLeveau commented on src/kili/utils/labels/point.py
> +    A point is a dict with keys 'x' and 'y', and corresponding values in pixels (int or float).
can you add this to the docstring?

2023-03-28 11:43 UTC, PierreLeveau approved these changes

2023-03-28 11:44 UTC, merged