tests: remove the pagination test
kili-technology/kili-python-sdk pull request #1126
Opened 2023-03-29 07:00 UTC by PierreLeveau

2023-03-29 07:05 UTC, Jonas1312 reviewed
I thought we wanted to decrease the test time by mocking the constants, but not completely remove it?

2023-04-07 11:28 UTC, Jonas1312 requested changes
ci doesn't pass

2023-04-28 13:08 UTC, PierreLeveau commented
I've added a unit test for the api_throttle and kept the burst_throttle for 1 integation test.

2023-04-28 13:42 UTC, Jonas1312 approved these changes

2023-04-28 13:44 UTC, merged