feat:added requierments.txt
kili-technology/kili-python-sdk pull request #1158
Opened 2023-04-11 12:10 UTC by manuelcgallucci

Completed requierments.txt with the libraries and the versions.

2023-04-11 12:41 UTC, PierreLeveau requested changes
the dependencies are in `setup.py`. All the dependencies already listed should be constrained to the major version, like `"tenacity>=8.0.0,<9.0.0"` for example.

2023-04-13 08:39 UTC, p-desaintchamas commented on docs/requirements.txt
> +kili==2.131.1
Not sure this should be hardcoded, else doc will never be generated for new versions of the sdk right ?

2023-04-18 12:05 UTC, manuelcgallucci commented
Added dependencies in setup.py, only limited to mayor releases, for libraries with minor releases only, the following was defined, example:
"cuid==0.4" in pip freeze, then in setup.py -> "cuid>=0.4,<0.5"

2023-04-18 12:58 UTC, PierreLeveau requested changes

2023-04-18 12:58 UTC, PierreLeveau commented on setup.py
> +    "pandas>=1.0.0",
here and below: missing upper bound `"pandas>=1.0.0,<2.0.0"`

2023-04-18 13:21 UTC, Jonas1312 requested changes
no need to change docs/requirements.txt

2023-04-18 15:57 UTC, Jonas1312 requested changes
the docs/requirements.txt is not needed anymore?

why do we lock some packages to minor versions and not major?

the package "filelock" is gone, need to merge/rebase and fix conflicts

2023-04-19 06:21 UTC, PierreLeveau commented
> the docs/requirements.txt is not needed anymore?
> 
> why do we lock some packages to minor versions and not major?
> 
> the package "filelock" is gone, need to merge/rebase and fix conflicts

indeed, the doc requirements should be restored.
There can be minor version locking if a feature we use is only present starting from a given minor version. This is also a common practice to lock the minor when the version is <1.0

2023-04-20 09:22 UTC, Jonas1312 approved these changes

2023-04-20 09:38 UTC, theodu approved these changes

2023-04-20 09:50 UTC, PierreLeveau approved these changes

2023-04-20 09:50 UTC, merged