Feature/ml 1255 video resolution in export kili
kili-technology/kili-python-sdk pull request #1334
Opened 2023-07-18 16:14 UTC by Jonas1312

2023-07-19 13:22 UTC, PierreLeveau approved these changes
Approved (but do not release before next Kili release)

2023-07-19 13:41 UTC, PierreLeveau commented on src/kili/services/export/tools.py
> +def is_geotiff_asset_with_lat_lon_coords(asset: Dict) -> bool:
should not be in this PR right?

2023-07-20 12:06 UTC, theodu commented on src/kili/services/export/format/base.py
> +                        " `normalized_coordinates=False`."
@PierreLeveau how did we handle the case of resolutions update in the front for geotiff images ? do we currently support it ? do we send a corrupted value or do we prevent the front from updating the resolutions for geotiff images ?
If we supported geotiff resolutions, we could unormalized  the vertices.

2023-07-20 12:06 UTC, theodu requested changes
.

2023-07-21 07:21 UTC, Jonas1312 commented on src/kili/services/export/format/base.py
> +                        " `normalized_coordinates=False`."
> if all N assets are geotiff, and that the parameters are valid wrt the export, we will test these two conditions N times
> 
> ```
> if has_one_geotiff_asset:
>     #test the 2 conditions
> ```

yep, I changed it for this:

```python
has_geotiff_asset = any(is_geotiff_asset_with_lat_lon_coords(asset) for asset in assets)
if has_geotiff_asset:
	...
```

2023-07-21 07:26 UTC, Jonas1312 commented on src/kili/services/export/media/image.py
> +        return image.size
> so here we suppose that we have already downloaded the image or the frames in the local machine right ?

first we look in the asset["resolution"], then local path yes (if user called kili.export_labels(with_assets=True)

2023-07-21 09:53 UTC, PierreLeveau commented on src/kili/services/export/format/base.py
> +                        " `normalized_coordinates=False`."
@theodu no specific treatment for geotiff images. We send the values, but they are not useful.

2023-07-21 12:39 UTC, theodu approved these changes

2023-07-24 05:23 UTC, PierreLeveau approved these changes

2023-07-27 13:07 UTC, PierreLeveau approved these changes

2023-07-27 13:40 UTC, merged