chore: backup
kili-technology/kili-python-sdk pull request #1353
Opened 2023-07-27 12:07 UTC by Jonas1312

2023-07-27 13:04 UTC, PierreLeveau requested changes

2023-07-27 13:04 UTC, PierreLeveau commented on src/kili/entrypoints/mutations/label/__init__.py
> +        variables = {"ids": ids}
we should batch the call for a number of labels > 100

2023-07-28 09:23 UTC, theodu approved these changes

2023-07-28 11:11 UTC, PierreLeveau requested changes

2023-07-28 11:11 UTC, PierreLeveau commented on tests/integration/entrypoints/mutations/test_labels.py
> +
i would put 101 labels and check that the client has been called twice

2023-07-28 13:19 UTC, theodu commented
```kili.delete_labels(ids=[])

GraphQLError: GraphQL error at index 0: WHERE parameter "id" has invalid "undefined" value"
```

we might need to do an early return if we have an empty list

2023-07-28 13:20 UTC, theodu requested changes
```kili.delete_labels(ids=[])
GraphQLError: GraphQL error at index 0: WHERE parameter "id" has invalid "undefined" value"
```

we might need to do an early return if we have an empty list

2023-07-31 07:42 UTC, theodu approved these changes

2023-07-31 15:11 UTC, merged