feat:added pascalvoc notebook
kili-technology/kili-python-sdk pull request #1390
Opened 2023-08-18 07:50 UTC by manuelcgallucci

2023-08-18 10:31 UTC, Jonas1312 requested changes
you have to do:
`python -m docs.utils convert recipes/importing_pascalvoc.ipynb`
in order to generate the markdown

once the markdown is generated, the pre-commit hook will run some checks to make sure the markdown is well formatted and integrated in mkdocs.yml, etc

Also, your notebook contains long outputs (from curl, pip) that make the tutorial harder to read. You can silence the cell output using `%%capture`

2023-08-18 12:59 UTC, Jonas1312 commented
@manuelcgallucci I generated the notebook

pull the branch locally, and run `pre-commit run --all-files` to fix the errors

2023-08-18 15:38 UTC, theodu requested changes
reviewed on https://app.reviewnb.com/kili-technology/kili-python-sdk/pull/1390/

2023-08-22 14:57 UTC, Jonas1312 approved these changes

2023-08-23 07:47 UTC, merged