refac:
kili-technology/kili-python-sdk pull request #1520
Opened 2023-10-04 15:26 UTC by Jonas1312

2023-10-05 12:44 UTC, PierreLeveau requested changes

2023-10-05 12:44 UTC, PierreLeveau commented on tests/integration/presentation/test_cloud_storage.py
> +    kili.kili_api_gateway = KiliAPIGateway(
use the `kili_api_gateway` conftest fixture (here and elsewhere)

2023-10-05 12:44 UTC, PierreLeveau commented on tests/integration/presentation/test_cloud_storage.py
> +    kili.kili_api_gateway = KiliAPIGateway(
use kili_api_gateway conftest fixture

2023-10-05 12:44 UTC, PierreLeveau commented on src/kili/presentation/client/cloud_storage.py
> +        data_connection_id = DataConnectionId(cloud_storage_connection_id)
There is a good amount of logic in the presentation, so we should probably add a `synchronize` use case.

2023-10-05 13:41 UTC, theodu approved these changes

2023-10-09 13:00 UTC, PierreLeveau approved these changes

2023-10-09 13:35 UTC, Jonas1312 commented on tests/integration/adapters/kili_api_gateway/test_cloud_storage.py
> +    gateway = KiliAPIGateway(graphql_client, http_client)
not here because we are testing at the gateway level, so we need to mock the layer below it (graphql client)

2023-10-09 13:35 UTC, merged