tests: moved e2e according to user type
kili-technology/kili-python-sdk pull request #1524
Opened 2023-10-05 14:54 UTC by PierreLeveau

2023-10-05 15:13 UTC, theodu approved these changes

2023-10-05 15:47 UTC, Jonas1312 requested changes
instead of moving all tests, we can create two kili client fixtures `kili` and `kili_admin` in tests/e2e/conftest.py

the kili_admin client use the kili_api_key_admin, and the normal kili client uses the kili_api_key_user

by default, all e2e tests use the `kili` fixture (it's already the case)

and if some e2e tests require admin rights, we pass the kili_admin client

2023-10-05 15:47 UTC, Jonas1312 commented on tests/e2e/test_tags.py
where has this test been moved to?

2023-10-06 09:20 UTC, Jonas1312 approved these changes

2023-10-06 09:23 UTC, Jonas1312 commented
do the e2e tests with exports fail when using the kili user client? (they should)

2023-10-06 09:24 UTC, PierreLeveau commented
> do the e2e tests with exports fail when using the kili user client? (they should)

there is no export e2e test

2023-10-06 09:28 UTC, Jonas1312 commented
> > do the e2e tests with exports fail when using the kili user client? (they should)
> 
> there is no export e2e test

notebooks

2025-08-05 08:28 UTC, closed without merging