feat(LOPS-1069): add methods to update integration
kili-technology/kili-python-sdk pull request #1609
Opened 2023-12-20 14:22 UTC by FannyGaudin

2023-12-21 09:32 UTC, PierreLeveau approved these changes

2024-01-02 09:49 UTC, baptiste-olivier commented
It may be a good idea to add a test to edit a data integration in `tests/e2e/test_cloud_storage.py`

2024-01-02 09:50 UTC, baptiste-olivier requested changes
Add a test to edit a data integration in tests/e2e/test_cloud_storage.py

2024-01-02 15:32 UTC, baptiste-olivier approved these changes

2024-01-02 15:45 UTC, merged