feat: reduce number of API calls to generate json responses
kili-technology/kili-python-sdk pull request #1710
Opened 2024-06-12 15:57 UTC by baptiste-olivier

2024-06-12 16:32 UTC, aurelienlombard approved these changes

2024-06-12 17:37 UTC, aurelienlombard requested changes

2024-06-12 17:37 UTC, aurelienlombard commented on src/kili/adapters/kili_api_gateway/asset/operations_mixin.py
> +                yield from self.list_assets_split(filters, fields, options, project_info)
Here you should put a return after to prevent from passing to the next part once these iterations are finished

2024-06-13 08:51 UTC, aurelienlombard requested changes

2024-06-13 08:51 UTC, aurelienlombard commented on src/kili/adapters/kili_api_gateway/asset/operations_mixin.py
> +            options.disable_tqdm, options.first, options.skip, min(options.batch_size, 10)
Now that we found a better solution, we could maybe put the limit at 100 for LLM projects and at 10 for video projects

2024-06-13 09:04 UTC, HNicolas approved these changes

2024-06-13 11:42 UTC, aurelienlombard approved these changes

2024-06-13 11:42 UTC, merged