Add list events method
kili-technology/kili-python-sdk pull request #1831
Opened 2024-12-11 11:30 UTC by florianlega

2024-12-11 13:21 UTC, FannyGaudin approved these changes

2024-12-11 13:21 UTC, FannyGaudin commented on src/kili/event/presentation/client/event.py
> +            user_id: Filter events by user.
user id ?

2024-12-11 15:17 UTC, baptiste-olivier requested changes
Don't forget to add : 
1. docs, you can check what is done for LLM, something similar should be enough
2. unit test, mocking graphql call with magic mock
3. e2e tests, as today we don't control what events are registered, and it is an important part for our customers (they react on it using webhooks / plugins)

The 3. could be done in a separate ticket once we know better the critical events

2024-12-12 13:01 UTC, baptiste-olivier approved these changes

2024-12-12 14:59 UTC, merged