AAU, on the CLI, when I go on the doc website, I see that I can download a zip file with basic ressources to launch all commands on the getting started
kili-technology/kili-python-sdk pull request #630
Opened 2022-07-25 11:15 UTC by FlorianLeRoyKili

2022-07-26 13:01 UTC, PierreLeveau commented
we won't publish that in the python-sdk, but directly in the doc. We will see the proper way to do it with @theodu

2022-07-28 10:26 UTC, theodu requested changes
To do this, we can modify the file: docs/cli/index.md in the python SDK which is the markdown file that generates the page https://python-sdk-docs.kili-technology.com/2.116/cli/
You can invite the reader to download the ressouces at https://storage.googleapis.com/kili-machine-learning-web/cli/CLI_Demo_Ressources.zip and accompany him to show how to launch commands

2022-07-28 11:55 UTC, FlorianLeRoyKili commented
https://github.com/kili-technology/kili-python-sdk/pull/629 should be merged before as the documentation has been written as if it was already merged.

2022-07-28 12:53 UTC, theodu approved these changes

2022-07-29 14:37 UTC, PierreLeveau submitted a review, later dismissed

2022-08-17 09:36 UTC, merged