Feature/ml 610 aamle on the python sdk when i call
kili-technology/kili-python-sdk pull request #655
Opened 2022-09-02 11:54 UTC by PierreLeveau

2022-09-08 08:29 UTC, mDuval1 approved these changes

2022-09-08 09:33 UTC, theodu requested changes

2022-09-08 09:33 UTC, theodu commented on kili/services/export/typing.py
> +InputType = Literal["text", "image"]
We should use this one everywhere. shouldn't we create a typing.py at the root of kili with common types like this one ?
And as the backend interpret it only in upper case, maybe have InputType = Literal["TEXT", "IMAGE", "PDF" , ect...]

2022-09-09 07:50 UTC, theodu approved these changes

2022-09-09 07:54 UTC, merged