Fix pyright
kili-technology/kili-python-sdk pull request #657
Opened 2022-09-13 07:23 UTC by crsegerie

2022-09-13 10:10 UTC, PierreLeveau requested changes

2022-09-13 10:10 UTC, PierreLeveau commented on kili/types.py
> +class License(TypedDict):
separate the replacement of dataclasses by the typedicts

2022-09-13 10:10 UTC, PierreLeveau commented on requirements.txt
>  typeguard
☝️ rm [recipes/download_google_drive](https://github.com/kili-technology/kili-python-sdk/pull/657/files#diff-aceaba362149f189bc98fbfe0646e9142bf339484a4c506985ac00e1b1de6dd9)

2022-09-13 10:10 UTC, PierreLeveau commented on requirements.txt
> +google-cloud
rm from baseline requirements

2022-09-13 10:10 UTC, PierreLeveau commented on test/services/export/fakes/fake_kili.py
> +from test.services.export.fakes.fake_data import asset_image  # type:ignore
rm # type:ignore

2022-09-13 10:10 UTC, PierreLeveau commented on test/test_client_project.py
> +            kili.get_project(ProjectId("this_project_id_do_not_exist"))
rm need to transtype

2022-09-13 15:09 UTC, crsegerie commented on kili/client.py
> +from kili.services.export.typing import ProjectId
in fact, It does not make sense to make this change considering the content of typing.py

2022-09-14 06:37 UTC, PierreLeveau approved these changes
LGTM, but wait until the release is done before merge

2022-09-15 11:19 UTC, merged