feat: add more information in mutation return values
kili-technology/kili-python-sdk pull request #860
Opened 2023-01-02 09:30 UTC by Jonas1312

@xczuba Please checkout that branch and run your notebook on it, in order to make sure the outputs are good for the tutorials

Modified methods:
- add_to_review
- send_back_to_queue
- update_properties_in_project

2023-01-02 10:57 UTC, theodu approved these changes

2023-01-02 11:40 UTC, PierreLeveau requested changes
I would add a few simple e2e tests to make sure it is working file.

2023-01-02 11:42 UTC, Jonas1312 commented
> I would add a few simple e2e tests to make sure it is working file.

Ok I will do that.

I also wait for @xczuba feedback

2023-01-02 17:05 UTC, Jonas1312 commented
@xczuba is good with the new return values for those methods

2023-01-03 08:09 UTC, PierreLeveau approved these changes

2023-01-03 08:09 UTC, merged