feat: add release notrebook test to end to end tests
kili-technology/kili-python-sdk pull request #890
Opened 2023-01-12 11:41 UTC by theodu

I removed the notebook from the release Kili functional testing template

2023-01-12 11:52 UTC, Jonas1312 approved these changes

2023-01-12 16:22 UTC, PierreLeveau requested changes

2023-01-12 16:22 UTC, PierreLeveau commented on tests/e2e/paginated_calls_project_lifecycle.ipynb
> +}
can you add a project deletion to clean up ?

2023-01-13 08:23 UTC, PierreLeveau approved these changes

2023-01-13 08:23 UTC, merged