test: fix windows unit testing
kili-technology/kili-python-sdk pull request #891
Opened 2023-01-12 13:39 UTC by Jonas1312

Windows specifities:
- requests.get() needs os.environ keys

2023-01-12 16:32 UTC, PierreLeveau requested changes

2023-01-12 16:32 UTC, PierreLeveau commented on src/kili/services/export/format/coco/__init__.py
> +            file_name=str("data" + "/" + file_name.parts[-1]),
```suggestion
            file_name=str(PosixPath("data") / file_name.parts[-1]),
```
should be working

2023-01-13 08:21 UTC, PierreLeveau approved these changes

2023-01-13 08:22 UTC, theodu approved these changes

2023-01-13 08:22 UTC, merged

2023-01-13 08:23 UTC, PierreLeveau commented on src/kili/services/export/format/coco/__init__.py
> +            file_name=str("data" + "/" + file_name.parts[-1]),
indeed this is `PurePosixPath` . I let you choose the solution. In any case, you should add a comment to says that the posix format is imposed by the COCO format.