docs: add workflow notebook
kili-technology/kili-python-sdk pull request #898
Opened 2023-01-16 09:46 UTC by Jonas1312

2023-01-16 09:59 UTC, theodu approved these changes

2023-01-16 13:55 UTC, theodu requested changes

2023-01-16 13:57 UTC, Jonas1312 commented on docs/sdk/tutorials/set_up_workflows.md
> +<a href="https://colab.research.google.com/github/kili-technology/kili-python-sdk/blob/master/recipes/tutorials/set_up_workflows.ipynb" target="_parent"><img src="https://colab.research.google.com/as
yes because this PR will move the notebooks to the recipes/tutorials folder

2023-01-17 11:50 UTC, xczuba commented on recipes/tutorials/set_up_workflows.ipynb
> +{
<p>Set up</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/kili-technology/kili-python-sdk/pull/898/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2023-01-17 11:50 UTC, xczuba commented on recipes/tutorials/set_up_workflows.ipynb
> +{
<p>Maybe we could add a link to the actual Basic project setup tutorial from here?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/kili-technology/kili-python-sdk/pull/898/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2023-01-17 11:50 UTC, xczuba commented on recipes/tutorials/set_up_workflows.ipynb
> +{
<p>This needs fixing:  ]"example3@example.com"]</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/kili-technology/kili-python-sdk/pull/898/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2023-01-17 12:07 UTC, Jonas1312 commented
we can merge :)

2023-01-17 15:04 UTC, merged