refactor: migrate queries in the graphql folder: Plugins
kili-technology/kili-python-sdk pull request #920
Opened 2023-01-19 12:46 UTC by theodu

2023-01-19 12:48 UTC, theodu commented
This is part of the big project to migrate all queries in a dedicated abstracted folder `graphql`.
The Plugin queries were implemented in a different way than other queries so it does not fully adapt to the GraphQLQuery class but we moved it anyway to finish the project

2023-01-19 12:49 UTC, theodu commented
to be tested before to merge

2023-01-19 12:53 UTC, PierreLeveau requested changes

2023-01-19 12:53 UTC, PierreLeveau commented on src/kili/graphql/operations/plugin/queries.py
> +    # pylint: disable=too-many-arguments,too-many-locals,too-many-instance-attributes
rm ?

2023-01-19 12:53 UTC, PierreLeveau commented on src/kili/graphql/operations/plugin/queries.py
> +    data: getPluginLogs(
indentation can be improved

2023-01-19 12:53 UTC, PierreLeveau commented on src/kili/graphql/operations/plugin/queries.py
> +    def logs(self, where: PluginLogsWhere, options: QueryOptions):
rename to get_logs

2023-01-24 08:36 UTC, PierreLeveau requested changes

2023-01-24 10:27 UTC, theodu commented
@PierreLeveau since your last review, I:
- fixed the ident on all queries file
- moved the fragement_builder function inside the GraphQLQuery class

2023-01-24 10:48 UTC, Jonas1312 approved these changes

2023-01-24 15:12 UTC, PierreLeveau approved these changes

2023-01-24 15:30 UTC, merged